### ISSUE TITLE
Issue solving with wildcard in MatchSpec

### ISSUE THREAD

**Issue by tl-hbk** [conda/rattler#812]
I've been trying to use `py-rattler` to replace some existing code I have using `libmamba` to solve for an environment.  One of the cases I've run into is that I have some internally built packages named something like `certifi-2024.8.1.dev-py_0` and when I want to solve and only have these internally built versions of certifi get picked, I would pass `certifi *.dev` for the `MatchSpec`.

```
specs = [
	"python 3.8",
	"certifi *.dev"
]
solved_deps = await solve_with_sparse_repodata(
	specs=[MatchSpec(s) for s in specs],
	sparse_repodata=sparse_repo_data,
	virtual_packages=virtual_packages,
	channel_priority=ChannelPriority.Disabled
)
```

with the above code I get the following exception

```
exceptions.SolverException: Cannot solve the request because of: No candidates were found for certifi * .dev.
```

Another situation where this seems to fail is if I have another package `foo` that contains the following in the `meta.yaml`

```
requirements:
  run:
    - python
    - certifi *.dev
```

Trying to solve for `foo` fails with a similar error as above

```
exceptions.SolverException: Cannot solve the request because of: foo cannot be installed because there are no viable options:
└─ foo ... would require
   └─ certifi * .dev, for which no candidates were found.
```

**Comment by baszalmstra** [comment]
Ah righto, the issue here is that the specifier `*.dev` is a regex version specifier which rattler does not support. Instead, rattler parses this as: `version=*, build=.dev`. Which indeed doesn't exist.

I think we should provide a better error message in this case. And potentially consider supporting regex version constraints. But I'm strongly against those because they can add substantial slowness and are susceptible to DDOS attacks.

Unfortunately, I also don't see a workaround for your case atm..

**Comment by wolfv** [comment]
Hmm @baszalmstra, this is just a glob operator if I'm not mistaken?

Regex should start with ^ and end with $ iirc

**Comment by baszalmstra** [comment]
We treat globs in versions as regexes.

**Comment by tl-hbk** [comment]
I ended up moving the tag I was using into the build string as that seems to fit my use-case fine.  Thanks for clarifying on the regex in the version string.
